import type { Person } from "@/lib/types";

const img = (file: string) => `/images/people/${file}`;

export const people: Record<string, Person> = {
  "shakeel-khan": {
    id: "shakeel-khan",
    name: "Shakeel Khan",
    role: "CEO and co-founder, Validate AI",
    bio: "Shakeel is the CEO of Validate AI, a community interest company he co-founded in 2019 with academics from Imperial College London and the University of Oxford. The organization advances AI validation to promote safe and trusted AI systems and fosters collaboration across private, public and academic sectors. With a decade in financial services he specialized in machine learning; as AI Capability Building Lead at the UK tax authority he developed trusted AI systems and an award-winning AI risk management methodology. He holds a Master’s in Operational Research from Strathclyde Business School.",
    image: img("shakeel-khan.jpg"),
  },
  "david-hand": {
    id: "david-hand",
    name: "Professor David Hand",
    role: "Co-founder, Validate AI",
    bio: "David Hand is a co-founder of Validate AI. He is Senior Research Investigator and Emeritus Professor of Mathematics at Imperial College London, where he previously held the Chair of Statistics. He serves on the Board of the UK Statistics Authority and the European Statistical Advisory Committee, is a former president of the Royal Statistical Society, and has received awards including the Guy Medal of the Royal Statistical Society.",
    image: img("david-hand.jpg"),
  },
  "marta-kwiatkowska": {
    id: "marta-kwiatkowska",
    name: "Professor Marta Kwiatkowska",
    role: "Co-founder, Validate AI",
    bio: "Marta Kwiatkowska is a co-founder of Validate AI and Professor of Computing Systems and Fellow of Trinity College, University of Oxford. She has made fundamental contributions to model checking for probabilistic systems and more recently to safety and robustness verification for neural networks. She led development of the PRISM model checker and is a Fellow of the Royal Society, ACM and the BCS.",
    image: img("marta-kwiatkowska.jpg"),
  },
  "tony-bellotti": {
    id: "tony-bellotti",
    name: "Dr Tony Bellotti",
    role: "Co-founder, Validate AI",
    bio: "Dr Tony Bellotti is a co-founder of Validate AI following the masterclass learning programme he delivered in machine learning at HMRC. He is Associate Professor in the School of Computer Science at University of Nottingham Ningbo, China. His research focuses on statistical models and machine learning applied to consumer credit risk, model risk and expected loss estimation.",
    image: img("tony-bellotti.jpg"),
  },
  "mark-kennedy": {
    id: "mark-kennedy",
    name: "Dr Mark Kennedy",
    role: "Co-Director, Imperial College London Data Science Institute",
    bio: "Dr Mark Kennedy is Co-Director of Imperial College London’s Data Science Institute and Director of Business Analytics. His research explores how innovations become real through categories, social ontologies and text and network analysis, including the emergence and impact of AI on organisations and society.",
    image: img("mark-kennedy.png"),
  },
  "zeynep-engin": {
    id: "zeynep-engin",
    name: "Dr Zeynep Engin",
    role: "Senior Research Associate, UCL Computer Science",
    bio: "Zeynep is a Senior Research Associate at UCL Computer Science and leads UCL’s Digital Ethics Forum. She founded the international Data for Policy conferences, is Editor-in-Chief of Data and Policy (Cambridge University Press), and Principal Investigator of the GovTech Lab. Her research focuses on digital ethics and algorithm assessment, particularly algorithmic fairness.",
    image: img("zeynep-engin.jpg"),
  },
  "ed-humpherson": {
    id: "ed-humpherson",
    name: "Ed Humpherson",
    role: "Director General for Regulation, UK Statistics Authority",
    bio: "Ed Humpherson was appointed Director General for Regulation in 2013 and heads the Office for Statistics Regulation, which provides independent regulation of official statistics in the UK to enhance public confidence in their trustworthiness, quality and value.",
    image: img("ed-humpherson.jpg"),
  },
  "giles-herdale": {
    id: "giles-herdale",
    name: "Giles Herdale",
    role: "Co-chair, Independent Digital Ethics Panel for Policing",
    bio: "Giles Herdale is co-chair of the Independent Digital Ethics Panel for Policing, advising on effective and ethical digital investigation. He has worked in policing at the NPIA, College of Policing and NPCC, where he set up and ran the DII programme, and now works as a consultant on crime, investigation and intelligence in the digital age.",
    image: img("giles-herdale.jpg"),
  },
  "gilbert-owusu": {
    id: "gilbert-owusu",
    name: "Dr Gilbert Owusu",
    role: "Data & AI Director, BT Group",
    bio: "Dr Gilbert Owusu is Data & AI Director at BT Group, with a strong track record applying AI and operational modelling to customer service improvement. He was President of the Operational Research Society in 2024 and is a visiting professor at the University of Essex and University of Leicester.",
    image: img("gilbert-owusu.jpg"),
  },
  "gavin-blackett": {
    id: "gavin-blackett",
    name: "Gavin Blackett",
    role: "Executive Director, Operational Research Society",
    bio: "Gavin Blackett is Executive Director of the Operational Research Society. He has worked in operational research throughout his career and has headed the OR Society staff for over 15 years. He is a Fellow of the OR Society.",
    image: img("gavin-blackett.png"),
  },
  "yike-guo": {
    id: "yike-guo",
    name: "Professor Yike Guo",
    role: "Founding Director, Imperial College London Data Science Institute",
    bio: "Professor Yike Guo has been Founding Director of the Data Science Institute, Imperial College London since 2014. He is a world-renowned researcher in big data analysis with broad experience applying data mining and machine learning in engineering and medicine.",
    image: img("yike-guo.jpg"),
  },
  "david-willetts": {
    id: "david-willetts",
    name: "The Rt Hon. Lord Willetts",
    role: "President, Resolution Foundation",
    bio: "The Rt Hon. Lord Willetts FRS is President of the Resolution Foundation. He served as Member of Parliament for Havant (1992–2015), as Minister for Universities and Science (2010–2014), and previously worked at HM Treasury and the No. 10 Policy Unit.",
    image: img("david-willetts.jpg"),
  },
  "michael-wooldridge": {
    id: "michael-wooldridge",
    name: "Professor Michael Wooldridge",
    role: "Head of Department of Computer Science, University of Oxford",
    bio: "Michael Wooldridge is Professor of Computer Science and Head of Department at the University of Oxford, and programme director for AI at the Alan Turing Institute. He has published more than 350 articles on AI and is a Fellow of the ACM, AAAI and EurAI.",
    image: img("michael-wooldridge.jpg"),
  },
  "aldo-faisal": {
    id: "aldo-faisal",
    name: "Dr Aldo Faisal",
    role: "Reader in Neurotechnology, Imperial College London",
    bio: "Dr Faisal is Reader in Neurotechnology at Imperial College London, where he leads the Brain & Behaviour Lab and directs the Behaviour Analytics Lab at the Data Science Institute.",
    image: img("aldo-faisal.jpg"),
  },
  "frankie-kay": {
    id: "frankie-kay",
    name: "Frankie Kay",
    role: "Office for National Statistics",
    bio: "Frankie is responsible for capability at the ONS, leading digital and workforce transformation to collect, securely store and analyse data from new sources and champion openness and data sharing for the public good.",
    image: img("frankie-kay.png"),
  },
  "jasmine-grimsley": {
    id: "jasmine-grimsley",
    name: "Dr Jasmine Grimsley",
    role: "Senior Data Scientist, ONS Data Science Campus",
    bio: "Dr Jasmine Grimsley links academia and government on data science for the public good. Her interests include the ethics of AI and using machine learning and NLP to solve real-world problems.",
    image: img("jasmine-grimsley.jpg"),
  },
  "jonathan-crook": {
    id: "jonathan-crook",
    name: "Professor Jonathan Crook",
    role: "Director, Credit Research Centre, University of Edinburgh",
    bio: "Jonathan Crook is Director of the Credit Research Centre and Deputy Dean at the University of Edinburgh Business School. He has researched credit scoring and credit availability since the late 1980s and is joint Editor of the Journal of the Operational Research Society.",
    image: img("jonathan-crook.jpg"),
  },
  "dan-kellett": {
    id: "dan-kellett",
    name: "Dan Kellett",
    role: "Head of Data Science, Capital One UK",
    bio: "Dan Kellett leads Capital One UK’s data science team, building models and data products across billions of customer transactions to unlock business opportunities and improve customer outcomes.",
    image: img("dan-kellett.jpg"),
  },
  "stan-boland": {
    id: "stan-boland",
    name: "Stan Boland",
    role: "Co-founder and CEO, Five",
    bio: "Stan Boland is co-founder and CEO of Five, developing autonomous vehicle technology in the UK. He was previously co-founder and CEO of Element 14 and Icera, acquired by Broadcom and NVIDIA respectively.",
    image: img("stan-boland.png"),
  },
  "iain-whiteside": {
    id: "iain-whiteside",
    name: "Dr Iain Whiteside",
    role: "Principal Scientist and Lead on Assurance, Five",
    bio: "Dr Iain Whiteside is Principal Scientist and Lead on Assurance at Five. He was formerly an assurance researcher in UAVs at NASA Ames and earned his PhD in formal software verification at the University of Edinburgh.",
    image: img("iain-whiteside.jpg"),
  },
  "michael-bronstein": {
    id: "michael-bronstein",
    name: "Professor Michael Bronstein",
    role: "Professor of Computing, Imperial College London",
    bio: "Michael Bronstein joined Imperial’s Department of Computing in 2018. His expertise is in geometric methods for data analysis with applications in machine learning, computer vision and imaging.",
    image: img("michael-bronstein.jpg"),
  },
  "pushmeet-kohli": {
    id: "pushmeet-kohli",
    name: "Pushmeet Kohli",
    role: "Head of research, DeepMind",
    bio: "Pushmeet Kohli heads research for AI for science and Robust & Reliable AI at DeepMind, with interests in safe and verified AI, probabilistic programming and healthcare applications.",
    image: img("pushmeet-kohli.jpg"),
  },
  "stephanie-hare": {
    id: "stephanie-hare",
    name: "Dr Stephanie Hare",
    role: "Independent researcher and broadcaster",
    bio: "Stephanie Hare is an independent researcher and broadcaster focused on technology, politics and history, with a PhD and MSc from the London School of Economics.",
    image: img("stephanie-hare.jpg"),
  },
  "carly-kind": {
    id: "carly-kind",
    name: "Carly Kind",
    role: "Director, Ada Lovelace Institute",
    bio: "Carly Kind is Director of the Ada Lovelace Institute, an independent research body with a mission to ensure data and AI work for people and society.",
    image: img("carly-kind.jpg"),
  },
  "martin-goodson": {
    id: "martin-goodson",
    name: "Martin Goodson",
    role: "Chief Scientist and CEO, Evolution AI",
    bio: "Martin is Chief Scientist and CEO of Evolution AI and Chair of the Royal Statistical Society Data Science Section.",
    image: img("martin-goodson.jpg"),
  },
  "tom-smith": {
    id: "tom-smith",
    name: "Tom Smith",
    role: "Managing Director, ONS Data Science Campus",
    bio: "Tom Smith is Managing Director at the Data Science Campus at the Office for National Statistics, with more than 20 years’ experience using data and analysis to improve public services.",
    image: img("tom-smith.jpg"),
  },
  "subramanian-ramamoorthy": {
    id: "subramanian-ramamoorthy",
    name: "Professor Subramanian Ramamoorthy",
    role: "University of Edinburgh",
    bio: "Professor Ramamoorthy holds a Chair of Robot Learning and Autonomy at the University of Edinburgh and is a Turing Fellow at the Alan Turing Institute.",
    image: img("subramanian-ramamoorthy.png"),
  },
  "reema-patel": {
    id: "reema-patel",
    name: "Reema Patel",
    role: "Associate Director, Ada Lovelace Institute",
    bio: "Reema is Associate Director at the Ada Lovelace Institute and leads public attitudes and deliberation research.",
    image: img("reema-patel.png"),
  },
  "matthew-jones": {
    id: "matthew-jones",
    name: "Dr C. Matthew Jones",
    role: "Senior Analytical Leader, Nationwide Building Society",
    bio: "Matthew’s team has pioneered application of AI in credit risk to enhance lending decisions in a fair, responsible and safe manner.",
    image: img("matthew-jones.png"),
  },
  "ara-darzi": {
    id: "ara-darzi",
    name: "Professor the Lord Darzi of Denham",
    role: "Imperial College London",
    bio: "Professor Darzi is Co-Director of the Institute of Global Health Innovation at Imperial College London and leads work including a global checklist for diagnostic AI.",
    image: img("ara-darzi.png"),
  },
  "hutan-ashrafian": {
    id: "hutan-ashrafian",
    name: "Hutan Ashrafian",
    role: "Chief Scientific Officer, Flagship Pioneering",
    bio: "Hutan Ashrafian is a clinician-scientist translating novel technologies in healthcare and policy, with leadership roles at Imperial College London and Flagship Pioneering.",
    image: img("hutan-ashrafian.png"),
  },
  "malvika-sharan": {
    id: "malvika-sharan",
    name: "Malvika Sharan",
    role: "The Alan Turing Institute",
    bio: "Malvika Sharan is a senior researcher at the Alan Turing Institute and co-leads The Turing Way, focused on reproducible, collaborative and ethical data science.",
    image: img("malvika-sharan.png"),
  },
  "maggie-philbin": {
    id: "maggie-philbin",
    name: "Maggie Philbin",
    role: "Co-founder, TeenTech",
    bio: "Maggie Philbin has worked in science and technology broadcasting for over 30 years and co-founded TeenTech to help young people build skills for a changing future.",
    image: img("maggie-philbin.png"),
  },
  "arthur-gwagwa": {
    id: "arthur-gwagwa",
    name: "Arthur Gwagwa",
    role: "Utrecht University Ethics Institute",
    bio: "Arthur Gwagwa is a doctoral researcher at Utrecht University Ethics Institute, researching socially disruptive technologies, AI and political polarization.",
    image: img("arthur-gwagwa.png"),
  },
  "paul-martynenko": {
    id: "paul-martynenko",
    name: "Paul Martynenko",
    role: "Deputy Chair, Alliance for Data Science Professionals",
    bio: "Paul Martynenko is Deputy Chair of the Alliance for Data Science Professionals and former President of BCS, The Chartered Institute for IT.",
    image: img("paul-martynenko.jpg"),
  },
  "yves-alexandre-de-montjoye": {
    id: "yves-alexandre-de-montjoye",
    name: "Professor Yves-Alexandre de Montjoye",
    role: "Associate Professor, Imperial College London",
    bio: "Yves-Alexandre de Montjoye is Associate Professor at Imperial College London and Special Adviser on AI and Data Protection to the European Commission.",
    image: img("yves-alexandre-de-montjoye.png"),
  },
  "marc-canellas": {
    id: "marc-canellas",
    name: "Marc Canellas",
    role: "Chair, IEEE-USA AI Policy Committee",
    bio: "Marc Canellas chairs the IEEE-USA AI Policy Committee and works as an Assistant Public Defender in Arlington County, Virginia.",
    image: img("marc-canellas.png"),
  },
};

export function getPerson(id: string): Person | undefined {
  return people[id];
}

export function getPeople(ids: string[]): Person[] {
  return ids.map((id) => people[id]).filter(Boolean) as Person[];
}
